FROM php:8.3-fpm

USER root

RUN apt-get update && \
    apt-get install -y apt-utils curl gzip

{extensions}

#####################################
#  Clean up APT:
#####################################
RUN \
    apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/html