#####################################
# PHP Imagick
#####################################
RUN apt-get install -y wget libmagickwand-dev imagemagick \
    && pecl install imagick \
    && docker-php-ext-enable imagick