#####################################
# PHP Imagick
#####################################
RUN apt-get install -y libmagickwand-dev imagemagick \
    && pecl install imagick \
    && docker-php-ext-enable imagick