################################################
# PHP PDO PostgreSQL
################################################
RUN apt-get install -y libpq-dev \
   && docker-php-ext-install pgsql \
   && docker-php-ext-install pdo_pgsql