services:
  go-app:
    container_name: go-app-container
    build:
      context: './'
      dockerfile: ./docker/Dockerfile
      args:
        # Используйте эту версию в go.mod
        - GO_VERSION=${GO_VERSION:-latest}
    restart: '${DOCKER_CONTAINER_RESTART}'
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true  # Для интерактивной работы
    ports:
      - "8080:8080"  # Порт приложения
    environment:
      - AIR_WORKDIR=/app
    command: air  # Запускаем air вместо go run
    networks:
      - application-network
