services:
  rabbitmq:
    # container_name: rabbitmq
    image: 'rabbitmq:${RABBITMQ_VERSION:-3}-management'
    hostname: '${RABBITMQ_HOSTNAME:-rabbitmq}'
    restart: '${DOCKER_CONTAINER_RESTART}'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-password}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq'
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
      - ${RABBITMQ_PORT:-5672}:5672
    networks:
      - application-network

volumes:
  rabbitmq:
    driver: local